# File: azure-pipelines.yml
# Date: 4-Jul-2019 jdw Created pipeline
#       8-Jul-2019 jdw add macos test/publish
#       8-Jul-2019 jdw templatize
#       9-Jul-2019 jdw add publish jobs
#      21-Jul-2019 jdw update to Py38
#      24-Nov-2020 jdw update to py39 remove py27
#      10-Oct-2024 mjt update to py310 remove py39
#
name: $(BuildDefinitionName)_$(Date:yyyyMMdd)$(Rev:.rr)

trigger:
  - master

pr:
  - master

schedules:
  - cron: "0 12 * * 0"
    displayName: Weekly Sunday build
    branches:
      include:
        - master
    always: true

jobs:
  - template: azure-template-tox-job.yml
    parameters: { tox: "format_pep8", python: "3.13", os: "linux", fixtures: 'mmseqs2'}
  - template: azure-template-tox-job.yml
    parameters: { tox: "lint_pylint", python: "3.13", os: "linux", fixtures: 'mmseqs2'}
  - template: azure-template-tox-job.yml
    parameters: { tox: "test_coverage", python: "3.13", os: "linux", fixtures: 'mmseqs2,mongodb'}
    #
  - template: azure-template-tox-job.yml
    parameters: { tox: "py313", python: "3.13", os: "linux", fixtures: 'mmseqs2,mongodb'}
  #
  - template: azure-template-tox-job.yml
    parameters: { tox: "py313", python: "3.13", os: "macos", fixtures: 'mmseqs2,mongodb'}
  #
  - template: azure-template-publish-job.yml
    parameters: { tox: "py313", python: "3.13", os: "linux" }
  #
